const CANCELLATION_REASONS = {
    INSURED_REQUESTED: 8,
    AMEND_PASSENGER_COUNT: 12,
    CHANGE_SCOPE_OF_COVER: 13,
    POLICY_NOT_TAKEN_UP: 14,
    VEHICLE_SOLD: 15,
    AMEND_INSURED_DETAILS: 18,
    AMEND_VEHICLE_DETAILS: 19,
    SUSPECTED_FRAUD: 20,
    NON_PAYMENT: 21,
    MISSING_KYC: 24,
    GOVERNMENT_REQUEST: 25,
    SUBJECT_MATTER_CEASED: 26,
    CHANGE_PERIOD_OF_INSURANCE: 27,
    INSURER_DECLINED_COVER: 28,
    WRITTEN_OFF: 29,
    STOLEN: 30,
};

export { CANCELLATION_REASONS };
