import { INSURERS } from './insurers.mjs';

const VEHICLE_TYPE_OPTIONS = {
    OWN_GOODS: 1,
    GENERAL_CARTAGE: 2,
    INSTITUTIONAL_VEHICLE: 3,
    SPECIAL_VEHICLE: 4,
    LIQUID_CARRYING_TANKERS: 5,
    ROAD_RISK_MOTOR_TRADE: 6,
};

const CLASS_A_CERTIFICATE_TYPE_OPTIONS = {
    PSV_UNMARKED: 1,
    TAXI: 8,
};

const CLASS_D_CERTIFICATE_TYPE_OPTIONS_WITH_PASSENGERS = {
    PRIVATE_MOTOR_CYCLE: 4,
    PSV_MOTOR_CYCLE: 9,
};

const CLASS_D_CERTIFICATE_TYPE_OPTIONS_COMMERCIAL = {
    COMMERCIAL_MOTOR_CYCLE: 10,
};

const CLASS_D_CERTIFICATE_TYPE_OPTIONS = {
    ...CLASS_D_CERTIFICATE_TYPE_OPTIONS_WITH_PASSENGERS,
    ...CLASS_D_CERTIFICATE_TYPE_OPTIONS_COMMERCIAL,
};

const CERTIFICATE_TYPE_OPTIONS = {
    ...CLASS_A_CERTIFICATE_TYPE_OPTIONS,
    ...CLASS_D_CERTIFICATE_TYPE_OPTIONS,
};

const VALUATION_COVER_TYPES_OPTION = {
    COMP: 100,
    TPTF: 300,
};

const COVER_TYPE_OPTIONS = {
    ...VALUATION_COVER_TYPES_OPTION,
    TPO: 200,
};

const MOTOR_CLASS_OPTIONS_WITH_CERTIFICATE_TYPE = {
    CLASS_A: 'A',
    CLASS_D: 'D',
};

const MOTOR_CLASS_OPTIONS = {
    ...MOTOR_CLASS_OPTIONS_WITH_CERTIFICATE_TYPE,
    CLASS_B: 'B',
    CLASS_C: 'C',
};

const MOTOR_CLASS_OPTIONS_WITH_PASSENGERS = [
    MOTOR_CLASS_OPTIONS.CLASS_A,
    MOTOR_CLASS_OPTIONS.CLASS_B,
    MOTOR_CLASS_OPTIONS.CLASS_D,
];

const MOTOR_CLASS_OPTIONS_WITH_TONNAGE = [MOTOR_CLASS_OPTIONS.CLASS_B, MOTOR_CLASS_OPTIONS.CLASS_D];

const KRA_PIN_REGEX = /^A\d{9}[A-Z]$/;

const COVERAGE_GAP_POLICIES = {
    BYPASS: 'bypass',
    STRICT: 'strict',
};

export {
    CERTIFICATE_TYPE_OPTIONS,
    CLASS_A_CERTIFICATE_TYPE_OPTIONS,
    CLASS_D_CERTIFICATE_TYPE_OPTIONS,
    CLASS_D_CERTIFICATE_TYPE_OPTIONS_COMMERCIAL,
    CLASS_D_CERTIFICATE_TYPE_OPTIONS_WITH_PASSENGERS,
    COVER_TYPE_OPTIONS,
    COVERAGE_GAP_POLICIES,
    INSURERS,
    KRA_PIN_REGEX,
    MOTOR_CLASS_OPTIONS,
    MOTOR_CLASS_OPTIONS_WITH_CERTIFICATE_TYPE,
    MOTOR_CLASS_OPTIONS_WITH_PASSENGERS,
    MOTOR_CLASS_OPTIONS_WITH_TONNAGE,
    VALUATION_COVER_TYPES_OPTION,
    VEHICLE_TYPE_OPTIONS,
};
