const VEHICLE_TYPE_OPTIONS = {
    OWN_GOODS: 1,
    GENERAL_CARTAGE: 2,
    INSTITUTIONAL_VEHICLE: 3,
    SPECIAL_VEHICLE: 4,
    LIQUID_CARRYING_TANKERS: 5,
    ROAD_RISK_MOTOR_TRADE: 6,
};

const CLASS_A_CERTIFICATE_TYPE_OPTIONS = {
    PSV_UNMARKED: 1,
    TAXI: 8,
};

const CLASS_D_CERTIFICATE_TYPE_OPTIONS_WITH_PASSENGERS = {
    PRIVATE_MOTOR_CYCLE: 4,
    PSV_MOTOR_CYCLE: 9,
};

const CLASS_D_CERTIFICATE_TYPE_OPTIONS_COMMERCIAL = {
    COMMERCIAL_MOTOR_CYCLE: 10,
};

const CLASS_D_CERTIFICATE_TYPE_OPTIONS = {
    ...CLASS_D_CERTIFICATE_TYPE_OPTIONS_WITH_PASSENGERS,
    ...CLASS_D_CERTIFICATE_TYPE_OPTIONS_COMMERCIAL,
};

const CERTIFICATE_TYPE_OPTIONS = {
    ...CLASS_A_CERTIFICATE_TYPE_OPTIONS,
    ...CLASS_D_CERTIFICATE_TYPE_OPTIONS,
};

const VALUATION_COVER_TYPES_OPTION = {
    COMP: 100,
    TPTF: 300,
};

const COVER_TYPE_OPTIONS = {
    ...VALUATION_COVER_TYPES_OPTION,
    TPO: 200,
};

const MOTOR_CLASS_OPTIONS = {
    CLASS_A: 'A',
    CLASS_B: 'B',
    CLASS_C: 'C',
    CLASS_D: 'D',
};

const MOTOR_CLASS_OPTIONS_WITH_PASSENGERS = [
    MOTOR_CLASS_OPTIONS.CLASS_A,
    MOTOR_CLASS_OPTIONS.CLASS_B,
    MOTOR_CLASS_OPTIONS.CLASS_D,
];

// TODO: update this list with the missing insurers
const INSURERS = {
    AIG: 12,
    AMACO: 11,
    APA: 14,
    BRITAM_INSURANCE: 15,
    CANNON: 32,
    CIC: 16,
    DEFINITE_INSURANCE: 49,
    DIRECTLINE: 18,
    FIDELITY_INSURANCE: 19,
    FIRST_ASSURANCE: 20,
    GA_INSURANCE: 21,
    GEMINIA: 22,
    HERITAGE: 42,
    ICEA_LION: 23,
    KENINDIA: 27,
    INTRAAFRICA: 24,
    JUBILEE_ALLIANZ: 26,
    KENYA_ALLIANCE: 29,
    KENYA_ORIENT: 28,
    MADISON: 30,
    MAYFAIR: 31,
    MUA: 35,
    MONARCH: 43,
    OLD_MUTUAL: 45,
    OCCIDENTAL: 33,
    PACIS: 34,
    PIONEER: 36,
    SANLAM: 39,
    STAR_DISCOVER: 47,
    TAKAFUL: 40,
    TRIDENT: 44,
};

export {
    VEHICLE_TYPE_OPTIONS,
    CERTIFICATE_TYPE_OPTIONS,
    COVER_TYPE_OPTIONS,
    INSURERS,
    MOTOR_CLASS_OPTIONS,
    CLASS_D_CERTIFICATE_TYPE_OPTIONS,
    CLASS_A_CERTIFICATE_TYPE_OPTIONS,
    CLASS_D_CERTIFICATE_TYPE_OPTIONS_WITH_PASSENGERS,
    CLASS_D_CERTIFICATE_TYPE_OPTIONS_COMMERCIAL,
    VALUATION_COVER_TYPES_OPTION,
    MOTOR_CLASS_OPTIONS_WITH_PASSENGERS,
};
